### ISSUE TITLE
Does pycvc support RSA-based certificate generation and verification? 

### ISSUE THREAD

**Issue by rathorearvind19** [polhenarejos/pycvc#1]
I am trying to create RSA based certificate but running into this issue here:

  File "*\Anaconda3\lib\site-packages\cvc\asn1.py", line 40, in make_tag
    return to_bytes(tag) + ASN1.calculate_len(len(b)) + bytearray(b)
TypeError: object of type 'int' has no len()

Command I used with RSA-2K key generated using openssl: 
cvc-create --role=cvca --type=at --chr=ZZATCVCA00001 --valid=365 --sign-key=ZZATCVCA00001.pkcs8 --scheme=RSA_v1_5_SHA_256

Does the package support RSA based certificates at all?

**Comment by polhenarejos** [comment]
Fixed in v1.2.3
