### ISSUE TITLE
CVC-CREATE: "--since" command line argument not supported

### ISSUE THREAD

**Issue by rathorearvind19** [polhenarejos/pycvc#4]
Even though the help content describes "--since" argument for valid_from date, it is not supported. Can we add the support for that? Can we also add support for valid_to date as well (in addition to # of days)? 

`Command: cvc-create --role=cvca --type=at --chr=ZZATCVCA00001 --since "2014/10/09" --valid=365 --sign-key=ZZATCVCA00001.pkcs8 --scheme=ECDSA_SHA_256`

> Traceback: 
> usage: cvc-create [-h] [--version] [-o FILENAME] [-r {cvca,dv_domestic,dv_foreign,terminal}] [-t {at,is,st}] [--valid VALID] -k FILENAME [--sign-as FILENAME] [--outer-as FILENAME] [--outer-key FILENAME]
>                   [-p FILENAME] [-q FILENAME] [--out-key FILENAME]
>                   [-s {ECDSA_SHA_1,ECDSA_SHA_224,ECDSA_SHA_256,ECDSA_SHA_384,ECDSA_SHA_512,RSA_v1_5_SHA_1,RSA_v1_5_SHA_256,RSA_v1_5_SHA_512,RSA_PSS_SHA_1,RSA_PSS_SHA_256,RSA_PSS_SHA_512}] [-c CHR]
>                   [-a REQ_CAR] [--write-dg17] [--write-dg18] [--write-dg19] [--write-dg20] [--write-dg21] [--write-dg22] [--rfu31] [--psa] [--read-dg1] [--read-dg2] [--read-dg3] [--read-dg4] [--read-dg5]
>                   [--read-dg6] [--read-dg7] [--read-dg8] [--read-dg9] [--read-dg10] [--read-dg11] [--read-dg12] [--read-dg13] [--read-dg14] [--read-dg15] [--read-dg16] [--read-dg17] [--read-dg18]
>                   [--read-dg19] [--read-dg20] [--read-dg21] [--read-dg22] [--install-qual-cert] [--install-cert] [--pin-management] [--can-allowed] [--privileged] [--rid] [--verify-community]
>                   [--verify-age] [--rfu5] [--rfu4] [--rfu3] [--rfu2] [--gen-qual-sig] [--gen-sig] [--read-iris] [--read-finger]
> cvc-create: error: unrecognized arguments: --since 2014/10/09

**Comment by polhenarejos** [comment]
Technically it is not complex doing so, but I am not confident on it. Usually, `since_date` should reflect the date of issuing and should not be used to fake dates in the future to cheat CA (like issuing certificates before a deadline of shutting down critical hash or scheme). Allowing arbitrary `since_date` is a potential security risk with unexpected consequences in the future.

In any case, from your comment I see you want to use `since_date` with a past date. Why do you need it? Just curious.

I'll fix `--since` description and add `--valid-to` flags.

**Comment by rathorearvind19** [comment]
I wanted to use a past date for testing reasons. 

But I do see a usecase for a future use. While provisioning certificates, we may want to specify a future date for certificate effective date so adding a since option will help. 

I understand and agree with your security concerns for past dates though.

**Comment by rathorearvind19** [comment]
Could we add the --since option to at least specify a future effective date?

**Comment by polhenarejos** [comment]
I pushed v1.2.6 to add it.

Note that `--valid` is renamed to `--days`.
