### ISSUE TITLE
CHAT byte in the certificates is not correctly configured

### ISSUE THREAD

**Issue by rathorearvind19** [polhenarejos/pycvc#5]
To configure read/write access permissions/authorization for different data groups, we pass --read-dgX arguments from the commandline while creating the certificate which gets reflected in the CHAT data (tag 53 in the certificate object). I don't see these arguments changing anything. The bits corresponding to different data groups are always set to 0. 
Can you fix this? Let me know if you need more detail.

**Comment by polhenarejos** [comment]
I cannot reproduce it. Can you paste the command are you using?

**Comment by rathorearvind19** [comment]
Yes. 
Here is the commandline.

`cvc-create --role=dv_domestic --type=is --chr=DETESTDVDE001 --valid=180 --sign-key=DETestingCV001.pkcs8 --scheme=ECDSA_SHA_256 --sign-as=DETestingCV001.cvcert --public-key=DETESTDVDE001.pub --read-dg3 --read-dg4`

Here is the certificate that is created. Look at the tag 53 (in **bold** and _italics_). Even when command was configured to authorize reads to DG3 and 4, it didn't get reflected in the CHAT byte (tag 53).  The value should have been 0x83 instead of 0x80. 

> '7f 4e 81 99 5f 29 01 00 42 0e 44 45 54 65 73 74 69 6e 67 43 56 30 30 31 7f 49 4f 06 0a 04 00 7f 00 07 02 02 02 02 03 86 41 04 9d a5 04 96 95 6e fd e5 05 af ac 0b f0 99 9e 9f 49 56 d6 ff 1f f3 1a a3 2d 4f 5a 86 1f 2a 24 03 bb 0e c4 75 37 91 4f 44 00 19 f3 b1 b1 70 87 2d c5 64 88 53 44 68 4e a9 e6 7c 68 b0 04 9b ce 7f 5f 20 0d 44 45 54 45 53 54 44 56 44 45 30 30 31 7f 4c 0e 06 09 04 00 7f 00 07 03 01 02 01 **_53 01 80_** 5f 25 06 02 03 00 04 02 05 5f 24 06 02 03 01 00 02 02 5f 37 40 56 2a d8 20 d9 28 98 18 9b 6d be 24 e2 72 28 1a a7 53 ad 07 14 4b 82 89 09 2b 9e 1a 33 0b ed 86 12 a7 cc b8 b2 22 46 49 db a9 99 4b ff ac 8e e2 2a e9 a3 33 e1 92 72 22 82 be 3c d3 fe 3d ed f8'

**Comment by polhenarejos** [comment]
Can you try with version 1.2.4? with rdg3 and rdg4 CHAT should be 0x0000000C00

**Comment by rathorearvind19** [comment]
Sorry about the late response. 
CHAT is 5 bytes if the terminal type is authentication terminal (AT) and for that access rights for data groups are being correctly configured as you mentioned above. However, when the terminal type is inspection system (IS), CHAT is 1 byte and for that --read-dg3, --read-dg4 arguments do not have any impact. Can you fix that?

**Comment by polhenarejos** [comment]
For IS terminals, cli parameters are `--read-iris` and `--read-fingerprint`.

**Comment by rathorearvind19** [comment]
Ok. thanks for that. 
I updated command line to use --read-iris and --read-finger (not --read-fingerprint) and don't see it having any impact on the CHAT byte. For example, for CVCA (command line below), I still see CHAT being configured as 53 01 C0 in the CVCA certificate. It should have been 53 01 C3. 

`cvc-create --role=cvca --type=is --chr=ZZATCVCA00001 --valid=365 --sign-key=ZZATCVCA00001.pkcs8 --scheme=ECDSA_SHA_256 --read-finger --read-iris`

**Comment by polhenarejos** [comment]
I pushed version 1.2.5 that fixes this bug.

Note that `--read-finger` is renamed to `--read-fingerprint`.

Also, I added `--chat` flag to specify custom CHAT bits.
